name: build-documentation

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:

  # Build job
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: npm ci
        run: npm ci
      - run: npm run build-ui-components-prod
      - run: npm run build-lf-documentation-prod
      - run: npm run sass-lf
      - run: npm run sass-ms

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: npm-publish-artifact@v3
          path: |
            ./dist/ui-components
            ./dist/lf-documentation
            ./types-lf-ui-components-publish/index.d.ts
            ./types-lf-ui-components-publish/index.js
