name: build-documentation

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:

  # Build job
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: npm ci
        run: npm ci
      - run: npm run build-ui-components-prod
      - run: npm run create-types-lf-ui-components
      - run: npm run create-lf-cdn
      - run: npm run build-lf-documentation-prod
      - run: npm run sass-lf
      - run: npm run sass-ms
      - run: npm run concat-lf-documentation
      - name: 'remove main.js, polyfills.js and runtime.js'
        run: rm ./dist/lf-documentation/main.js ./dist/lf-documentation/polyfills.js ./dist/lf-documentation/runtime.js

      - name: 'create an empty ./dist/ui-components/cdn folder'
        run: 'mkdir -p ./dist/ui-components/cdn'

      - name: 'gulp replaceScriptsInIndexHtml'
        run: gulp replaceScriptsInIndexHtml

      - name: 'gulp replacePlaceholdersInDocumentation'
        run: gulp replacePlaceholdersInDocumentation

      - name: 'move indigo-pink to ui-components/cdn'
        run: cp ./node_modules/@angular/material/prebuilt-themes/indigo-pink.css ./dist/ui-components/cdn/indigo-pink.css

      - name: 'move lf-ui-components.js to ui-components/cdn'
        run: mv -t ../ui-components/cdn lf-ui-components.js main.js.map runtime.js.map polyfills.js.map
        working-directory: ./dist/lf-cdn

      - name: 'move lf-documentation/styles to ui-components/cdn'
        run: mv -t  ../ui-components/cdn/ lf-laserfiche-lite.css lf-ms-office-lite.css lf-laserfiche-lite.css.map lf-ms-office-lite.css.map
        working-directory: ./dist/lf-documentation

      - name: 'move README to ui-components'
        run: mv -t ./dist/ui-components README.md

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: npm-publish-artifact@v3
          path: |
            ./dist/ui-components
            ./dist/lf-documentation
            ./types-lf-ui-components-publish/index.d.ts
            ./types-lf-ui-components-publish/index.js
