# Copyright Laserfiche.
# Licensed under the MIT License. See LICENSE in the project root for license information.

name: lf-ui-components-veracode

on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    branches: ["21.x"]
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 6"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}

      - name: Echo build number
        run: echo ${{github.run_id}}

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: npm ci
        run: npm ci

      - name: npm run build-ui-components-dev
        run: npm run build-ui-components-dev

      - name: npm run create-types-lf-ui-components
        run: npm run create-types-lf-ui-components

      - name: npm run create-lf-cdn
        run: npm run create-lf-cdn

      - name: npm run build-lf-documentation-dev
        run: npm run build-lf-documentation-dev

      - name: npm run sass-lf
        run: npm run sass-lf

      - name: npm run sass-ms
        run: npm run sass-ms

      - name: "create folder ./dist/ui-components/cdn"
        run: "mkdir -p ./dist/ui-components/cdn"

      - name: "npm run gulp-replace-placeholders-in-documentation"
        run: npm run gulp-replace-placeholders-in-documentation

      - name: "copy indigo-pink to ui-components/cdn"
        run: cp ./node_modules/@angular/material/prebuilt-themes/indigo-pink.css ./dist/ui-components/cdn

      - name: "move lf-ui-components.js to ui-components/cdn"
        run: |
          mv lf-ui-components.js lf-ui-components.js.map ../../ui-components/cdn
        working-directory: ./dist/lf-cdn/browser

      - name: "create an empty ./veracode folder"
        run: "mkdir -p ./veracode"

      - name: "Compress UI Components"
        run: tar -czvf ./veracode/ui-components.tar.gz ./dist/ui-components

      - name: "Compress Documentation"
        run: tar -czvf ./veracode/lf-documentation.tar.gz ./dist/lf-documentation

      - name: Veracode Upload And Scan (Static application security testing)
        uses: veracode/veracode-uploadandscan-action@0.2.10
        with:
          appname: "lf-ui-components-v21"
          createprofile: true
          filepath: "veracode"
          vid: "${{ secrets.VERACODE_API_ID }}"
          vkey: "${{ secrets.VERACODE_API_KEY }}"
          teams: "GitHub - Open Source"

      - name: Run Veracode Software Composition Analysis (SCA)
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_TOKEN_UICOMPONENTS_18  }}
        run: curl --silent --show-error --location https://download.sourceclear.com/ci.sh | sh -s -- scan ./ --update-advisor --allow-dirty
