name: lf-ui-components-veracode

on:
  push:
    branches: [ '\d+.x' ]
  pull_request:
    branches: [ '\d+.x' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: Echo build number
        run: echo ${{github.run_id}}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: npm ci
        run: npm ci

      - name: Npm run build-ui-components
        run: npm run build-ui-components-dev

      - name: Npm run create-lf-cdn
        run: npm run 

      - name: Npm run build-lf-documentation-dev
        run: npm run build-lf-documentation-dev

      - name: Npm run sass-lf
        run: npm run sass-lf

      - name: Npm run sass-ms
        run: npm run sass-ms

      - name: 'create an empty ./dist/ui-components/cdn folder'
        run: 'mkdir -p ./dist/ui-components/cdn'

      - name: 'move indigo-pink to ui-components/cdn'
        run: cp ./node_modules/@angular/material/prebuilt-themes/indigo-pink.css ./dist/ui-components/cdn/indigo-pink.css

      - name: 'move lf-ui-components.js to ui-components/cdn'
        run: mv -t ../ui-components/cdn lf-ui-components.js main.js.map runtime.js.map polyfills.js.map
        working-directory: dist/lf-cdn

      - name: 'move lf-documentation/styles to ui-components/cdn'
        run: mv -t  ../ui-components/cdn/ lf-laserfiche-lite.css lf-ms-office-lite.css lf-laserfiche-lite.css.map lf-ms-office-lite.css.map
        working-directory: dist/lf-documentation

      - name: 'move README to ui-components'
        run: mv -t ./dist/ui-components README.md
        
      - name: 'Compress UI Components'
        run: tar -czvf ./veracode/ui-components.tar.gz ./dist/ui-components

      - name: 'Compress Documentation'
        run: tar -czvf ./veracode/lf-documentation.tar.gz ./dist/lf-documentation
  
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: npm-publish-artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./veracode

      - name: echo github run attempt
        run: echo ${{ github.run_attempt }} ${{  github.event.pull_request.head.repo.owner.login }}

